### ISSUE TITLE
Subscribe and handle field-data event named `RawCaptureCreated`

### ISSUE THREAD

**Issue by arunbakt** [Greenstand/webmap-query-service-consumer#2]
Add ability to connect to RabbitMQ messaging service and write a subscriber that listens to field-data event named `RawCaptureCreated`.  `RawCaptureCreated` is an event published by field-data service whenever a raw capture is created, please see [here](https://github.com/Greenstand/treetracker-field-data/blob/master/server/models/RawCapture.js).

On consuming the event, process it and create and write an entry to the `raw_capture_feature` table.

**Comment by mstefany16** [comment]
Can I work on this? I'm not able to assign it to myself

**Comment by arunbakt** [comment]
Hi @mstefany16 , are you part of the microservices working group? Can you share your name or ping me in Slack?
