### ISSUE TITLE
Review Service Code

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/webmap-query-service-consumer#23]
Perform a review of the development state of this service, including the following tasks

Update to node 16, test for compatibility, fix compatibility issues

Check CI/CD - installed and working?
* test, release, deploy automation for dev environment
* test when a new PR is submitted
* Manual deployment to testing environment

Fix linting errors if present
* Run linter and fix errors

Review state of testing 
* Do unit tests exist
* Do integration test exist
* Do tests run successfully
* Is test running straightforward
* Review test coverage

Review state of open PRs
* Can they be merged
* Resolve conflicts

Typescript 
* Evaluate appropriateness of this service for conversation to typescript - positives and negatives

Microservices implementation structural review
* Is our software architecture approach to microservices implementation working well for this project

**Comment by dadiorchen** [comment]
To manually deploy, there is a button and form requiring inputting tag/branch name to deploy

**Comment by dadiorchen** [comment]
```
I have not used code coverage tools before, is there a specific one I should use for this?
```

I ever used `istabel` for test coverage, it's good, for Jest, there are built-in tool for test coverage .
