### ISSUE TITLE
Compute region assignment on raw capture feature creation

### ISSUE THREAD

**Issue by arunbakt** [Greenstand/webmap-query-service-consumer#3]
When creating an entry for raw_capture_feature during consuming the `RawCaptureCreated` event, compute and store the region assignment (table `region_assignment`).

Region assignment is the association of raw capture id (`map_feature_id` column in `region_assignment`), zoom_level and region_id.
For e.g. when a new capture is created its location is used to retrieve the appropriate region ids from `regions` table and joined with `region_zoom` table (which is a collection of zoom levels for a given region) and each resulting row will be assigned the map_feature_id (raw capture id). 

NOTE:  To see sql used and  get more context, please refer to this [javascript file](https://github.com/Greenstand/treetracker-web-map-api/blob/master/src/cron/assign-new-trees-to-clusters.js) that creates the existing data in table named `tree_region` which is equivalent to what we need to create with `region_assignment`.

**Comment by dadiorchen** [comment]
I'm working on this issue

**Comment by dadiorchen** [comment]
@arunbakt do we need to consider also the capture event? Not just the raw_capture?

**Comment by arunbakt** [comment]
Yes, I would think so @dadiorchen . Both raw_capture_feature and capture_feature would require regions assignment I believe. But that could be a separate ticket.
