### ISSUE TITLE
Subscribe and process`TokensAssigned` Event

### ISSUE THREAD

**Issue by arunbakt** [Greenstand/webmap-query-service-consumer#5]
The `TokensAssigned` event would be emitted by the Wallet API service. The format of this event is to be finalized and not yet concrete. But the idea is, captures processed and verified would have eligible tokens and these tokens are owned by or associated with wallets. Thus, capture records are associated to the wallets and tokens so that clients using the data can query capture features by wallet or token. 

When a creation or transfer of tokens occurs in wallet api, TokensAssigned event is generated. The format of this event will be roughly of the following kind (concrete format will be known soon but will be more or less the same as follows):

{
  "type": "TokensAssigned",
  "wallet_name": "joeswallet",
  "entries": [ 
{  "capture_id": "63e00bca-8eb0-11eb-8dcd-0242ac130003", "token_id": "9d7abad8-8eb0-11eb-8dcd-0242ac130003"  },
{ "capture_id": "8533b704-8eb0-11eb-8dcd-0242ac130003", "token_id":"a5799d94-8eb0-11eb-8dcd-0242ac130003" } ]
}

On handling this event, process and update `capture_feature` with the wallet name and that of the token_id. When the processing is complete, mark the event as `handled`.

**Comment by dadiorchen** [comment]
@arunbakt something needs to confirm with you.

* The table `capture_feature` is the table needs to be updated, right?

```
       Column        |           Type           | Collation | Nullable | Default
---------------------+--------------------------+-----------+----------+---------
 id                  | uuid                     |           | not null |
 lat                 | numeric                  |           | not null |
 lon                 | numeric                  |           | not null |
 location            | geometry(Point,4326)     |           | not null |
 field_user_id       | bigint                   |           | not null |
 field_username      | character varying        |           | not null |
 device_identifier   | character varying        |           |          |
 attributes          | jsonb                    |           |          |
 tracking_session_id | uuid                     |           |          |
 map_name            | jsonb                    |           |          |
 token_id            | uuid                     |           |          |
 wallet_name         | character varying        |           |          |
 created_at          | timestamp with time zone |           | not null |
 updated_at          | timestamp with time zone |           | not null |
 species_name        | character varying        |           |          |
 capture_taken_at    | timestamp with time zone |           |          |
```

* What do you mean by 'mark the event as handled'?

**Comment by arunbakt** [comment]
That is correct @dadiorchen.
