### ISSUE TITLE
Subscribe and process `MapNameAssigned` event

### ISSUE THREAD

**Issue by arunbakt** [Greenstand/webmap-query-service-consumer#6]
1) We run a scheduled job to assign impact producer to raw_capture and capture on a daily basis, which gives us point of production for this event.
3) After assigning impact producer,  the scheduled job will emit the 'map name assigned' message
4) Assigning  impact producer is immutable.  (These are maps based on immutable data.)
5) The webmap consumer will look up the mapname for the stakeholder assigned as impact producer

Message Format:
{
"type": "ImpactProducerAssigned",
"impact_producer_id": "<stakeholder_id>",
"map_feature_ids": [ "a5799d94-8eb0-11eb-8dcd-0242ac130003", "0ee1ebdc-8eb2-11eb-8dcd-0242ac130003"],
"map_feature_kind": "raw_capture"
}

Database Schema
map : {
   impact_producer: <stakeholder.map>,
   impact_manager: <stakeholder.map> // skip implementation of this line for now
}

Original spec, super-ceded by above
> Map features such as `capture`, `raw_capture` and `tree` are sometimes assigned map names. For e.g. users of a program to plant trees in a city might want to search those tracking activity by giving a map name to their tracking. To search by the map name so that the web-map can show the tracked plants, we want to associate the map-features (raw_captures, captures and trees) with map name.
> 
> Currently, the details about the system that would emit and publish this event is unclear. But we know we want to subscribe to an event that would give the ids of the features such as capture_id, raw_capture_id, tree_id and their associated map name. The following is spec for this event:
> {
>   "type": "MapNameAssigned",
>   "map_name": "Freetown",
>   "map_feature_ids": [ "a5799d94-8eb0-11eb-8dcd-0242ac130003", "0ee1ebdc-8eb2-11eb-8dcd-0242ac130003"],
>   "map_feature_kind": "raw_capture"
> }
> 
> Note: map_feature_kind could be "raw_capture", "capture", or "tree". For practical purposes, the event for map_Feature kind capture is applicable to raw_capture as well since capture is a subset of raw_capture.
> 
> Subscribe to the MapNameAssigned event in RabbitMQ messaging system and process the event by updating the raw_capture, capture tables with the map_name for the give map_feature_ids (this is the id of the raw_capture or capture). In case of map_feature_kind `tree`, update just the `tree` table with the map_name.  Once processed mark the event as `handled`.

**Comment by dadiorchen** [comment]
@arunbakt I am still not clear about this, who/which service is the producer of this event? And when it would be emitted?

**Comment by dadiorchen** [comment]
Can you help explain a bit?

**Comment by arunbakt** [comment]
@dadiorchen ,  I am not clear on who creates a `map_name` that gets associated to raw_capture_feature and capture_feature, in web-map-query service. So not sure who assigns map_name (by that which service creates the map_name). But the consumer would be web-map-query-service.

**Comment by dadiorchen** [comment]
@ZavenArra
